baseURL = "https://papermod-1rp.pages.dev/"
languageCode = "it"
title = "Test PaperMod"
theme = "hugo-PaperMod-master"
[pagination]
  pagerSize = 10
[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Archivio"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    name = "Cerca"
    url = "/search/"
    weight = 4
  [[menu.main]]
    name = "Shop"
    url = "/shop/"
    weight = 5
  [[menu.main]]
    name = "Chi Siamo"
    url = "/about/"
    weight = 6
  [[menu.main]]
    name = "Contatti"
    url = "/contatti/"
    weight = 7
  [[menu.main]]
    name = "Servizi"
    url = "/servizi/"
    weight = 8
    [[menu.main]]
      name = "Web Design"
      url = "/servizi/web-design/"
      parent = "Servizi"
      weight = 1
    [[menu.main]]
      name = "SEO"
      url = "/servizi/seo/"
      parent = "Servizi"
      weight = 2
  [[menu.main]]
    name = "Risorse"
    url = "/risorse/"
    weight = 9
    [[menu.main]]
      name = "Guide"
      url = "/risorse/guide/"
      parent = "Risorse"
      weight = 1
    [[menu.main]]
      name = "Tools"
      url = "/risorse/tools/"
      parent = "Risorse"
      weight = 2
