backend:
  name: github
  repo: cialdecompatibili-netizen/papermod
  branch: main
  base_url: https://papermod-1rp.pages.dev
  auth_endpoint: api/auth
media_folder: static/images
public_folder: /images
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: string, required: false}
      - {label: Body, name: body, widget: markdown}
