backend:
  name: github
  repo: cialdecompatibili-netizen/papermod
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Post
    folder: content/posts
    create: true
    fields:
      - {label: Titolo, name: title, widget: string}
      - {label: Data, name: date, widget: datetime}
      - {label: Contenuto, name: body, widget: markdown}
      - {label: Tags, name: tags, widget: list, required: false}