backend:
  name: github
  repo: cialdecompatibili-netizen/papermod
  branch: main
  auth_type: pkce
  app_id: Ov23liQBPb6SCwsxGhvs

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}